import html,json,urllib.request,datetime
u='idlirshkurti'
def get(url): return json.load(urllib.request.urlopen(urllib.request.Request(url,headers={'User-Agent':'profile-card'})))
p=get(f'https://api.github.com/users/{u}');r=get(f'https://api.github.com/users/{u}/repos?per_page=100&type=owner')
rows=[('role','Data Scientist'),('location','Germany'),('languages','Python · SQL · R · TypeScript'),('data','DuckDB · PostgreSQL · pandas'),('ml/ai','Forecasting · LLM systems · evals'),('platform','Kubernetes · Azure · FastAPI · Temporal'),('repos',p['public_repos']),('stars',sum(x['stargazers_count'] for x in r)),('followers',p['followers']),('updated',datetime.datetime.now(datetime.UTC).strftime('%Y-%m-%d'))]
art=open('ascii-art.txt').read().splitlines()[:26]
def card(path,bg,fg,muted,accent):
 stats=''.join(f"<text x='32' y='{92+i*23}' class='l'>{k}</text><text x='388' y='{92+i*23}' text-anchor='end' class='v'>{v}</text>" for i,(k,v) in enumerate(rows));portrait=''.join(f"<tspan x='448' y='{52+i*11}'>{html.escape(line)}</tspan>" for i,line in enumerate(art));svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="720" height="360" viewBox="0 0 720 360"><style>.t{{font:700 24px monospace;fill:{fg}}}.s,.l{{font:13px monospace;fill:{muted}}}.v{{font:700 13px monospace;fill:{fg}}}.a{{font:8px monospace;fill:{accent}}}</style><rect width="720" height="360" rx="16" fill="{bg}"/><rect x="18" y="18" width="684" height="324" rx="11" fill="none" stroke="{muted}" stroke-opacity=".5"/><line x1="416" y1="39" x2="416" y2="321" stroke="{muted}" stroke-opacity=".5"/><text x="32" y="57" class="t">idlirshkurti@github</text>{stats}<text class="a" xml:space="preserve">{portrait}</text><text x="448" y="323" class="s">ASCII profile portrait</text></svg>''';open(path,'w').write(svg)
card('dark_mode.svg','#0d1117','#e6edf3','#8b949e','#58a6ff');card('light_mode.svg','#ffffff','#1f2328','#59636e','#0969da')
